apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: optimairwing
  namespace: optimairwing
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.optimairwing.app
        - optimairwing.app
      secretName: optimairwing-tls
  rules:
    - host: optimairwing.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: optimairwing-api
                port:
                  number: 80
    - host: api.optimairwing.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: optimairwing-api
                port:
                  number: 80
