apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: optimairwing
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
images:
  - name: ghcr.io/optimairwing/api
    newTag: latest
