apiVersion: v1
kind: Secret
metadata:
  name: optimairwing-secrets
  namespace: optimairwing
type: Opaque
stringData:
  JWT_SECRET: "cambiar-en-produccion"
  ADMIN_SECRET_KEY: "cambiar-en-produccion"
  API_KEY: "cambiar-en-produccion"
  STRIPE_SECRET_KEY: ""
  STRIPE_WEBHOOK_SECRET: ""
  SENTRY_DSN: ""
  RESEND_API_KEY: ""
  PGHOST: "optimairwing-postgres"
  PGPORT: "5432"
  PGDATABASE: "optimairwing"
  PGUSER: "optimairwing"
  PGPASSWORD: "cambiar-en-produccion"
  REDIS_URL: "redis://optimairwing-redis:6379"
  GEMINI_API_KEY: ""
